version: '3'

services:
  movie-service:
    # build:
    #   context: ./movie-service
    #   dockerfile: Dockerfile
    image: registry.gitlab.com/cinema_agile/mvp:latest
    container_name: mvp
    environment: 
      # DATABASE_HOST: postgres:5432 
      # DATABASE_NAME: postgres 
      DATABASE_HOST: movie_db:3306
      DATABASE_NAME: movie_base
      DATABASE_USER: movie_user
      DATABASE_PWD: movie_user_pwd
    ports:
      - 8080:8080
    depends_on: 
      # - postgres
      - movie_db
    networks: 
      - backend
 
  # postgres:
  #   image: postgres:latest
  #   container_name: postgres
  #   environment:
  #     - POSTGRES_USER=postgres 
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=postgres
  #   ports:
  #     - '5432:5432'
  #   networks:
  #     - backend

  movie_db:
    image: mysql:5.7
    container_name: movie_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movie_base
      MYSQL_USER: movie_user
      MYSQL_PASSWORD: movie_user_pwd
    ports:
      - 3306:3306
    networks: 
      - backend      
networks:
  backend:    